### ISSUE TITLE
Change default branch to `master`

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-frame#20]
As of last week, GitHub now [allows pages to be deployed from the `master` branch](https://github.com/blog/2228-simpler-github-pages-publishing) as opposed to the `gh-pages` branch. This allows us to use the more standard `master` name instead of having just the `gh-pages` branch (less obvious of a location) or worse yet, keeping both around. This is a relatively simple change in GitHub settings, but may require some minor local git branch juggling.

**Comment by meetar** [comment]
Sure, sounds good – if you update your old `master` branch (or delete it, and I'll make a new one) then I'll switch it over.

**Comment by louh** [comment]
`master` branch here is now up-to-date with `gh-pages`.

**Comment by meetar** [comment]
Okay, will switch once https://github.com/tangrams/tangram-frame/pull/23 is
tested and merged.

**Comment by meetar** [comment]
Default branch and Github Pages build branch switched.

**Comment by louh** [comment]
We can actually delete `gh-pages` now - there's no benefit to keeping it around at this point (and can only create more confusion).

**Comment by meetar** [comment]
Yep, my plan is to poke around to make sure nothing else is linking
directly to "blob/gh-pages" for any reason before I do that.
