### ISSUE TITLE
Speed up loading of libraries.

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-frame#29]
We have this ability to specify a custom version of Tangram. Based on the version of Tangram, we then load the correct version of Leaflet, followed by other utility libraries that depend on Leaflet. This creates a network loading graph that looks like this:

<img width="1275" alt="screenshot 2016-11-29 16 00 42" src="https://cloud.githubusercontent.com/assets/2553268/20728792/59b2ff3a-b64d-11e6-96e6-6f560a84b517.png">

Note that libraries are loading _synchronously_. We should be able to improve on this.

1. If the Tangram version is known (e.g. a version number, or the default Tangram library), then we can load Tangram and Leaflet at the same time.
2. Leaflet-hash and mapzen-ui are not dependent on each other, only on Leaflet. They can be loaded at the same time, after Leaflet is loaded.

This cuts four subsequent network requests happening one after the other down to two (since two requests will be happening at the same time). Optimistically we can cut the loading time of libraries down to almost half of the current time.

I'd be interested in seeing how effective this is because if we can show that there's not a significant loading speed increase to do things this way I can then do something similar (loading arbitrary Tangram versions) for Tangram Play.

**Comment by meetar** [comment]
Hmm, good point! I already have everything wired to be injected into the page in the right order, so I think this would just be a matter of splitting out the script loads, and making each injection also depend on a promise coming back from the appropriate onload().
