### ISSUE TITLE
fractional zooms in URL are rounding to the nearest integer

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-frame#30]
`tangram-frame` seems to be rounding a fractional zoom in a URL to an integer 

https://tangrams.github.io/tangram-frame/?url=https://mapzen.com/api/scenes/22/64/resources/default.yaml#5.9/33.948/66.482

The example above will open up to z6, not z5.9 as I intended.

I'd prefer this to remain a fraction. I often will set a zoom level to just below an integer where where a zoom-dependent style change kicks in. If tangram-frame changes this, the style change is immediately apparent. 

(Curious, is this tangram-frame or leaflet?)

**Comment by meetar** [comment]
It was a leaflet default – I agree that having the option to link straight to a fractional zoom is preferable.
