### ISSUE TITLE
maxBounds

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-frame#33]
would be helpful to be able to access `maxBounds`to retain focus on a certain area. http://leafletjs.com/reference.html#map-maxbounds

**Comment by burritojustice** [comment]
https://github.com/tangrams/tangram-frame/pull/34

**Comment by meetar** [comment]
Hey John, looks good – there are a couple of tweaks I'd like to make, for instance I don't want to enforce a default maxBounds so I think I'll refactor a bit.

**Comment by meetar** [comment]
Resolved with https://github.com/tangrams/tangram-frame/pull/35
