### ISSUE TITLE
Display title of scene, if available

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-frame#47]
Follows #40 (we need a mechanism for retrieving scene API metadata). Ported from https://github.com/tangrams/tangram-play/issues/682.

> include scene name in the <title> tag of the map ... so people can give and get a meaningful name in their browser tab and search history, and distinguish amongst Tangram Play and View instances open in their browsers

After retrieving a scene from the API, read the scene's title property and populate the `<title>` tag.

**Comment by meetar** [comment]
added with https://github.com/tangrams/tangram-frame/commit/59d2dea1cea73962bf81d37657a0c9ba93a12c48
