### ISSUE TITLE
When a scene is retrieved via the `?api=` parameter, display the scene name in the page title.

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-frame#51]
Example from Tangram Play https://github.com/tangrams/tangram-play/blob/1273a2fd64d07dc33d8d06086f80de70f3525781/src/js/tangram-play.js#L314-L320

**Comment by meetar** [comment]
Hmm, this should be done by this line:

https://github.com/tangrams/tangram-frame/blob/master/main.js#L128

… not sure why it's not working.

**Comment by louh** [comment]
Oh, I tried it again. I think it _is_ working; I should have double checked!

Let's modify this so that the title is in the format of `[scene name] · Tangram Viewer`. This is so that  it's still clear (like, in a browser history list, or bookmarks, or search results) what the base page is.
